"""add_currentStatusName

Revision ID: 8d8f12a2ebb9
Revises: 3dc22fc5bdfb
Create Date: 2025-03-03 21:09:50.301042+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8f12a2ebb9'
down_revision: Union[str, None] = '3dc22fc5bdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_info', sa.Column('currentStatusName', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_info', 'currentStatusName')
    # ### end Alembic commands ###
