"""add_markers

Revision ID: 1c4caa668446
Revises: d35b763bcffb
Create Date: 2025-07-01 22:37:50.491417+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4caa668446'
down_revision: Union[str, None] = 'd35b763bcffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_info', sa.Column('markersString', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_info', 'markersString')
    # ### end Alembic commands ###
