"""add_bot_id

Revision ID: 28717921b320
Revises: 794ff6880a82
Create Date: 2025-10-17 15:23:39.607305+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28717921b320'
down_revision: Union[str, None] = '794ff6880a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twin_projects', sa.Column('bot_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twin_projects', 'bot_id')
    # ### end Alembic commands ###
