"""add_redash_variable

Revision ID: d35b763bcffb
Revises: 1121291e7a3e
Create Date: 2025-04-26 09:31:10.031980+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd35b763bcffb'
down_revision: Union[str, None] = '1121291e7a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_info', sa.Column('redash_variable', sa.JSON(), nullable=True))
    op.add_column('call_info', sa.Column('redash_result', sa.JSON(), nullable=True))
    op.alter_column('call_info', 'dialogResult',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_info', 'dialogResult',
               existing_type=sa.String(length=500),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('call_info', 'redash_result')
    op.drop_column('call_info', 'redash_variable')
    # ### end Alembic commands ###
