"""add_new_column

Revision ID: 3dc22fc5bdfb
Revises: 7477f9279220
Create Date: 2025-03-02 10:01:27.448434+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc22fc5bdfb'
down_revision: Union[str, None] = '7477f9279220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_info', sa.Column('status', sa.String(length=225), nullable=True))
    op.add_column('call_info', sa.Column('confirmation', sa.String(length=225), nullable=True))
    op.add_column('call_info', sa.Column('resultsString', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_info', 'resultsString')
    op.drop_column('call_info', 'confirmation')
    op.drop_column('call_info', 'status')
    # ### end Alembic commands ###
