"""create_db

Revision ID: 7477f9279220
Revises: 
Create Date: 2025-03-01 13:43:30.328106+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7477f9279220'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twin_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('twin_login', sa.String(length=225), nullable=False),
    sa.Column('twin_password', sa.String(length=225), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twin_login')
    )
    op.create_table('call_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('botId', sa.UUID(), nullable=True),
    sa.Column('timezone', sa.Integer(), nullable=True),
    sa.Column('nps', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('mainCallDuration', sa.Integer(), nullable=True),
    sa.Column('robotCallDuration', sa.Integer(), nullable=True),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('isIncoming', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('startedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finishedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('project', sa.String(length=225), nullable=False),
    sa.ForeignKeyConstraint(['project'], ['twin_projects.twin_login'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_info_createdAt'), 'call_info', ['createdAt'], unique=False)
    op.create_index(op.f('ix_call_info_finishedAt'), 'call_info', ['finishedAt'], unique=False)
    op.create_index(op.f('ix_call_info_nps'), 'call_info', ['nps'], unique=False)
    op.create_index(op.f('ix_call_info_startedAt'), 'call_info', ['startedAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_info_startedAt'), table_name='call_info')
    op.drop_index(op.f('ix_call_info_nps'), table_name='call_info')
    op.drop_index(op.f('ix_call_info_finishedAt'), table_name='call_info')
    op.drop_index(op.f('ix_call_info_createdAt'), table_name='call_info')
    op.drop_table('call_info')
    op.drop_table('twin_projects')
    # ### end Alembic commands ###
