"""add_telegram_settings

Revision ID: 1b47cc103fd2
Revises: 28717921b320
Create Date: 2025-10-18 22:02:43.993621+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b47cc103fd2'
down_revision: Union[str, None] = '28717921b320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twin_projects', sa.Column('tg_chat_id', sa.String(), nullable=True))
    op.add_column('twin_projects', sa.Column('tg_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twin_projects', 'tg_token')
    op.drop_column('twin_projects', 'tg_chat_id')
    # ### end Alembic commands ###
