"""add_date_start

Revision ID: 794ff6880a82
Revises: 2d78ea9ab1b0
Create Date: 2025-10-13 21:31:15.787000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794ff6880a82'
down_revision: Union[str, None] = '2d78ea9ab1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twin_projects', sa.Column('date_start', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE twin_projects SET date_start = '2025-02-24'")
    # ###
    op.alter_column('twin_projects', 'date_start', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twin_projects', 'date_start')
    # ### end Alembic commands ###
