"""add_fields

Revision ID: 2d78ea9ab1b0
Revises: 1c4caa668446
Create Date: 2025-07-03 22:41:09.069122+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d78ea9ab1b0'
down_revision: Union[str, None] = '1c4caa668446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twin_projects', sa.Column('fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twin_projects', 'fields')
    # ### end Alembic commands ###
